Server:
  RunMode: debug
  HttpPort: 8080
  ReadTimeout: 60
  WriteTimeout: 60
Database:
  DBType: mysql
  Username: root
  Password: rootroot
  Host: 127.0.0.1:3306
  DBName: uniswap_testnet
  TablePrefix: uniswap_
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
UniSwap:
  Rpc: wss://mainnet.gateway.tenderly.co
  WEthAddress : 0xadfaf
  PositionManagerAddress: 0xc36442b4a4522e871399cd717abdd847ab11fe88
  SwapRouterAddress : 0xe592427a0aece92de3edee1f18e0157c05861564

